//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForms.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class kz {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kz() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinForms.language.kz", typeof(kz).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аккаунт.
        /// </summary>
        internal static string аккаут {
            get {
                return ResourceManager.GetString("аккаут", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сіз.
        /// </summary>
        internal static string Вы {
            get {
                return ResourceManager.GetString("Вы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аты бойынша.
        /// </summary>
        internal static string именем {
            get {
                return ResourceManager.GetString("именем", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пайдаланушы.
        /// </summary>
        internal static string Пользователь {
            get {
                return ResourceManager.GetString("Пользователь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с.
        /// </summary>
        internal static string с {
            get {
                return ResourceManager.GetString("с", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тіркелдіңіз.
        /// </summary>
        internal static string создали {
            get {
                return ResourceManager.GetString("создали", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сақталды.
        /// </summary>
        internal static string Сохранено {
            get {
                return ResourceManager.GetString("Сохранено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бар.
        /// </summary>
        internal static string существует {
            get {
                return ResourceManager.GetString("существует", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to осындай.
        /// </summary>
        internal static string таким {
            get {
                return ResourceManager.GetString("таким", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сәтті.
        /// </summary>
        internal static string успешно {
            get {
                return ResourceManager.GetString("успешно", resourceCulture);
            }
        }
    }
}
